version: "3"
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sushi
      - POSTGRES_USER=sushi
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  flaskapp:
    build: ./flaskapp
    volumes:
      - ./flaskapp/app:/flaskapp/app
    environment:
      - ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=sushi
      - POSTGRES_USER=sushi
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  proxy:
    build: ./proxy
    ports:
      - "8080:80"